apiVersion: v1
appVersion: 3.0.0
description: nfs-volume-provisioner is an out-of-tree dynamic volume provisioner for Kubernetes. You can use it to quickly & easily deploy shared storage that works almost anywhere.
name: nfs-volume-provisioner
version: 0.0.1
maintainers:
- name: ndtech
  email: admin@22ndtech.com
home: https://github.com/22ndtech/nfs-volume-provisioner
sources:
- https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/tree/master/deploy/helm
- https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner
keywords:
- nfs
- storage
